# Generated by Django 3.0.6 on 2020-05-29 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancia', models.CharField(max_length=200, unique=True, verbose_name='Substância')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('altura', models.IntegerField(verbose_name='Altura (cm)')),
                ('medicacao_diaria', models.CharField(max_length=400, verbose_name='Medicação Diária')),
                ('tempo_rec', models.IntegerField(verbose_name='Tempo de Recuperação (dias)')),
                ('alergias', models.ManyToManyField(to='coletas.Alergia')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coletas.Cidade')),
                ('comorbidades', models.ManyToManyField(to='coletas.Comorbidade')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coletas.Quadro')),
                ('sintomas', models.ManyToManyField(to='coletas.Sintoma')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coletas.Tratamento')),
            ],
        ),
    ]
