# Generated by Django 3.0.6 on 2020-05-29 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadro',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tratamento',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='quadro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Quadro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Tratamento'),
        ),
    ]
