# Generated by Django 3.0.6 on 2020-06-02 08:42

import coletas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0003_auto_20200529_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(coletas.models.AutoDesc, models.Model),
        ),
        migrations.CreateModel(
            name='Forma_Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancia', models.CharField(max_length=200, unique=True, verbose_name='Substância')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='exame',
            field=models.FileField(null=True, upload_to='exames/%Y/%m/%d/', verbose_name='Exame'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='outros_tratamentos',
            field=models.CharField(blank=True, max_length=400, verbose_name='Outros Tratamentos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='questionario',
            field=models.FileField(null=True, upload_to='questionarios/%Y/%m/%d/', verbose_name='Questionário'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Alergia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comorbidades',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Comorbidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicacao_diaria',
            field=models.CharField(blank=True, max_length=400, verbose_name='Medicação Diária'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Sintoma'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Fase'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tratamentos',
            field=models.ManyToManyField(null=True, to='coletas.Forma_Tratamento'),
        ),
    ]
