# Generated by Django 3.0.6 on 2020-06-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0004_auto_20200602_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forma_tratamento',
            options={'verbose_name': 'Forma de Tratamento', 'verbose_name_plural': 'Formas de Tratamento'},
        ),
        migrations.AlterModelOptions(
            name='tratamento',
            options={'verbose_name': 'Tratamento antigo'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='quadro',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='exame',
            field=models.FileField(blank=True, null=True, upload_to='exames/%Y/%m/%d/', verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='questionario',
            field=models.FileField(blank=True, null=True, upload_to='questionarios/%Y/%m/%d/', verbose_name='Questionário'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Tratamento'),
        ),
        migrations.DeleteModel(
            name='Quadro',
        ),
    ]
