# Generated by Django 3.0.6 on 2020-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0005_auto_20200602_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name': 'Alergia a remédio - se sim, qual(is):', 'verbose_name_plural': 'Alergias a medicamento'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Teve sintomas - se sim, qual(is):', 'verbose_name_plural': 'Sintomas'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='form_consentimento',
            field=models.FileField(null=True, upload_to='questionarios/%Y/%m/%d/', verbose_name='Formulário de Consentimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome completo'),
        ),
    ]
