# Generated by Django 3.0.6 on 2020-06-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0006_auto_20200616_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name': 'Alergias a medicamento', 'verbose_name_plural': 'Alergia a remédio - se sim, qual(is):'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Sintomas', 'verbose_name_plural': 'Teve sintomas - se sim, qual(is):'},
        ),
    ]
