# Generated by Django 3.0.6 on 2020-06-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0007_auto_20200616_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name': 'Alergia a remédio - se sim, qual(is):'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Teve sintomas - se sim, qual(is):'},
        ),
    ]
