# Generated by Django 3.0.6 on 2020-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0008_auto_20200616_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Alergia', verbose_name='Alergia a remédio - se sim, qual(is)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='form_consentimento',
            field=models.FileField(null=True, upload_to='consentimento/%Y/%m/%d/', verbose_name='Formulário de Consentimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Sintoma', verbose_name='Teve sintomas - se sim, qual(is)'),
        ),
    ]
