# Generated by Django 3.0.6 on 2020-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0009_auto_20200616_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
