# Generated by Django 3.0.6 on 2020-06-18 22:16

import coletas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0011_auto_20200613_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(coletas.models.AutoDesc, models.Model),
        ),
        migrations.AddField(
            model_name='paciente',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Origem'),
        ),
    ]
