# Generated by Django 3.0.6 on 2020-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0012_auto_20200618_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origem',
            options={'verbose_name': 'Indicação', 'verbose_name_plural': 'Indicações'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='diag_final',
            field=models.CharField(blank=True, max_length=200, verbose_name='Diagnóstico Final'),
        ),
    ]
