# Generated by Django 3.0.6 on 2020-07-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0014_auto_20200723_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias_Sintoma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletas.Paciente')),
                ('sintomas1', models.ManyToManyField(blank=True, null=True, related_name='DiasSin1', to='coletas.Sintoma', verbose_name='dia')),
                ('sintomas2', models.ManyToManyField(blank=True, null=True, related_name='DiasSin2', to='coletas.Sintoma', verbose_name='dia')),
                ('sintomas3', models.ManyToManyField(blank=True, null=True, related_name='DiasSin3', to='coletas.Sintoma', verbose_name='dia')),
            ],
        ),
    ]
