# Generated by Django 3.0.6 on 2020-07-26 16:35

import coletas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0016_auto_20200726_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_sintoma',
            name='intervalo',
            field=models.CharField(default=coletas.models.Dias_Sintoma.calc_intervalo, max_length=32, verbose_name='Intervalor'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='sintomas1',
            field=models.ManyToManyField(blank=True, null=True, related_name='DiasSin1', to='coletas.Sintoma', verbose_name='Dias 1, 4 e 7'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='sintomas2',
            field=models.ManyToManyField(blank=True, null=True, related_name='DiasSin2', to='coletas.Sintoma', verbose_name='Dias 2, 5 e 8'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='sintomas3',
            field=models.ManyToManyField(blank=True, null=True, related_name='DiasSin3', to='coletas.Sintoma', verbose_name='Dias 3, 6 e 9'),
        ),
    ]
