# Generated by Django 3.0.6 on 2020-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0018_remove_dias_sintoma_intervalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas01',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas02',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas03',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas04',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas05',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas06',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas07',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas08',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas09',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas10',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas11',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas12',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas13',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas14',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas15',
        ),
    ]
