# Generated by Django 3.0.6 on 2020-08-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0019_auto_20200726_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dias_sintoma',
            name='sintomas2',
        ),
        migrations.RemoveField(
            model_name='dias_sintoma',
            name='sintomas3',
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia1',
            field=models.BooleanField(blank=True, null=True, verbose_name='D1'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia2',
            field=models.BooleanField(blank=True, null=True, verbose_name='D2'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia3',
            field=models.BooleanField(blank=True, null=True, verbose_name='D3'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia4',
            field=models.BooleanField(blank=True, null=True, verbose_name='D4'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia5',
            field=models.BooleanField(blank=True, null=True, verbose_name='D5'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia6',
            field=models.BooleanField(blank=True, null=True, verbose_name='D6'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia7',
            field=models.BooleanField(blank=True, null=True, verbose_name='D7'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia8',
            field=models.BooleanField(blank=True, null=True, verbose_name='D8'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia9',
            field=models.BooleanField(blank=True, null=True, verbose_name='D9'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='sintomas1',
            field=models.ManyToManyField(blank=True, null=True, related_name='DiasSin1', to='coletas.Sintoma', verbose_name='Sintoma'),
        ),
    ]
