# Generated by Django 3.0.6 on 2020-08-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0022_auto_20200801_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia1',
            field=models.BooleanField(blank=True, default=False, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia2',
            field=models.BooleanField(blank=True, default=False, verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia3',
            field=models.BooleanField(blank=True, default=False, verbose_name='D3'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia4',
            field=models.BooleanField(blank=True, default=False, verbose_name='D4'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia5',
            field=models.BooleanField(blank=True, default=False, verbose_name='D5'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia6',
            field=models.BooleanField(blank=True, default=False, verbose_name='D6'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia7',
            field=models.BooleanField(blank=True, default=False, verbose_name='D7'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia8',
            field=models.BooleanField(blank=True, default=False, verbose_name='D8'),
        ),
        migrations.AlterField(
            model_name='dias_sintoma',
            name='dia9',
            field=models.BooleanField(blank=True, default=False, verbose_name='D9'),
        ),
    ]
