# Generated by Django 3.0.6 on 2020-08-01 23:02

import coletas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0023_auto_20200801_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Diagnóstico final',
                'verbose_name_plural': 'Diagnosticos Finais',
            },
            bases=(coletas.models.AutoDesc, models.Model),
        ),
        migrations.CreateModel(
            name='Medicoes_dia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicao', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Frequência cardiáca', 'Frequência cardiáca'), ('Frequência respiratória', 'Frequência respiratória'), ('Pressão Arterial', 'Pressão Arterial'), ('Saturação de O2', 'Saturação de O2')], default='Temperatura', max_length=32, verbose_name='Tipo de Medição')),
                ('dia1', models.FloatField(verbose_name='D1')),
                ('dia2', models.FloatField(verbose_name='D2')),
                ('dia3', models.FloatField(verbose_name='D3')),
                ('dia4', models.FloatField(verbose_name='D4')),
                ('dia5', models.FloatField(verbose_name='D5')),
                ('dia6', models.FloatField(verbose_name='D6')),
                ('dia7', models.FloatField(verbose_name='D7')),
                ('dia8', models.FloatField(verbose_name='D8')),
                ('dia9', models.FloatField(verbose_name='D9')),
            ],
            options={
                'verbose_name': 'Sintoma por dias',
                'verbose_name_plural': 'Sintomas por dias',
            },
        ),
        migrations.AlterModelOptions(
            name='dias_sintoma',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diag_final',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tratamento',
        ),
        migrations.AddField(
            model_name='forma_tratamento',
            name='posologia',
            field=models.CharField(max_length=100, null=True, verbose_name='Posologia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sang',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=16, null=True, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.DeleteModel(
            name='Tratamento',
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletas.Paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagfinal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.DiagFinal', verbose_name='Diagnóstico Final'),
        ),
    ]
