# Generated by Django 3.0.6 on 2020-08-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0024_auto_20200801_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dias_sintoma',
            options={'verbose_name': 'Sintoma por dias', 'verbose_name_plural': 'Sintomas por dias'},
        ),
        migrations.AlterModelOptions(
            name='medicoes_dia',
            options={'verbose_name': 'Medição por dias', 'verbose_name_plural': 'Medições por dias'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Negro', 'Negro'), ('Pardo', 'Pardo'), ('Indígena', 'Indígena'), ('Amarelo', 'Amarelo')], default='Branco', max_length=32, verbose_name='Etnia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='medicao',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Frequência cardiáca', 'Frequência cardiáca'), ('Frequência respiratória', 'Frequência respiratória'), ('Pressão Arterial Sistólica', 'Pressão Arterial Sistólica'), ('Pressão Arterial Diastólica', 'Pressão Arterial Diastólica'), ('Saturação de O2', 'Saturação de O2')], default='Temperatura', max_length=32, verbose_name='Tipo de Medição'),
        ),
    ]
