# Generated by Django 3.0.6 on 2020-08-16 21:31

import coletas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0025_auto_20200806_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas de Exame',
            },
            bases=(coletas.models.AutoDesc, models.Model),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Negro', 'Negro'), ('Pardo', 'Pardo'), ('Indígena', 'Indígena'), ('Amarelo', 'Amarelo')], default='Branco', max_length=32, verbose_name='Etnia'),
        ),
        migrations.CreateModel(
            name='ResultadosExames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val1', models.FloatField(verbose_name='Valor')),
                ('val2', models.FloatField(verbose_name='Valor')),
                ('val3', models.FloatField(verbose_name='Valor')),
                ('met1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m1', to='coletas.MetricasExame')),
                ('met2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m2', to='coletas.MetricasExame')),
                ('met3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m3', to='coletas.MetricasExame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletas.Paciente')),
            ],
        ),
    ]
