# Generated by Django 3.0.6 on 2020-08-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0027_auto_20200816_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosexames',
            name='met3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m3', to='coletas.MetricasExame'),
        ),
        migrations.AddField(
            model_name='resultadosexames',
            name='val3',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='resultadosexames',
            name='val1',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='resultadosexames',
            name='val2',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
    ]
