# Generated by Django 3.0.6 on 2020-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0028_auto_20200816_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosexames',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
    ]
