# Generated by Django 3.0.6 on 2020-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0029_resultadosexames_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia1',
            field=models.FloatField(blank=True, null=True, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia2',
            field=models.FloatField(blank=True, null=True, verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia3',
            field=models.FloatField(blank=True, null=True, verbose_name='D3'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia4',
            field=models.FloatField(blank=True, null=True, verbose_name='D4'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia5',
            field=models.FloatField(blank=True, null=True, verbose_name='D5'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia6',
            field=models.FloatField(blank=True, null=True, verbose_name='D6'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia7',
            field=models.FloatField(blank=True, null=True, verbose_name='D7'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia8',
            field=models.FloatField(blank=True, null=True, verbose_name='D8'),
        ),
        migrations.AlterField(
            model_name='medicoes_dia',
            name='dia9',
            field=models.FloatField(blank=True, null=True, verbose_name='D9'),
        ),
    ]
