# Generated by Django 3.0.6 on 2021-01-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0030_auto_20201006_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agravantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Habito agravante',
                'verbose_name_plural': 'Habitos agravantes',
            },
        ),
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome popular')),
                ('nome_tecnico', models.CharField(max_length=300, unique=True, verbose_name='Nome Técnico')),
            ],
            options={
                'verbose_name': 'Teve alguma destas doenças',
                'verbose_name_plural': 'Teve alguma destas doenças',
            },
        ),
        migrations.CreateModel(
            name='Medicoes_Estudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Medicação em Estudo',
                'verbose_name_plural': 'Medicações em Estudo',
            },
        ),
        migrations.CreateModel(
            name='Medicoes_Indicadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Medicação regular',
                'verbose_name_plural': 'Medicações Regulares',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='dt_ini_sintomas',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início dos Sintomas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dt_nasc',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='internado_antes',
            field=models.CharField(choices=[('Não', 'Não'), ('Enfermaria', 'Enfermaria'), ('UTI', 'UTI')], default='Não', max_length=32, verbose_name='Já ficou internado para tratamento do Covid'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='internado_tempo',
            field=models.CharField(choices=[('Não foi internado', 'Não foi internado'), ('00 - 05 dias', '00 - 05 dias'), ('05 - 10 dias', '05 - 10 dias'), ('10 - 15 dias', '10 - 15 dias'), ('+ 15 dias', '+ 15 dias')], default='Não foi internado', max_length=32, verbose_name='Tempo de internação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='jah_covid',
            field=models.CharField(choices=[('Não', 'Não'), ('1º Contato', '1º Contato'), ('2º Contato', '2º Contato'), ('3º ou + vezes', '3º ou + vezes'), ('POSITIVO APÓS SOROLOGIA SEM SINTOMAS', 'POSITIVO APÓS SOROLOGIA SEM SINTOMAS')], default='Não', max_length=128, verbose_name='Já teve Covid 19'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_test_covid',
            field=models.CharField(choices=[('Não fez por Motivos Financeiros', 'Não fez por Motivos Financeiros'), ('Não fez pq não teve sintomas', 'Não fez pq não teve sintomas'), ('Não fez pq os sintomas estavam leves', 'Não fez pq os sintomas estavam leves'), ('Não fez pq não nenhum médico solicitou', 'Não fez pq não nenhum médico solicitou'), ('Fez o Teste Rapido', 'Fez o Teste Rapido'), ('Fez o RT PCR', 'Fez o RT PCR'), ('Fez a Sorologia', 'Fez a Sorologia')], default='Não fez por Motivos Financeiros', max_length=128, verbose_name='Motivo para o Teste Covid'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='proc_ajuda_antes',
            field=models.CharField(choices=[('Não', 'Não'), ('Publico', 'Publico'), ('Privado', 'Privado'), ('Publico e Privado', 'Publico e Privado')], default='Não', max_length=32, verbose_name='Procurou ajuda antes de iniciar nosso tratamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tomou_antes',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tomou Medicações em Estudo antes do tratamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='agravantes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coletas.Agravantes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='jah_doencas',
            field=models.ManyToManyField(null=True, to='coletas.Doencas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medic_est_associada',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Medicoes_Estudo', verbose_name='Medicações em Estudo indicadas ou tomadas por contra própria'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medic_reg_indicada',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Medicoes_Indicadas', verbose_name='Medicações regulares indicadas por outros profissionais da saúde'),
        ),
    ]
