# Generated by Django 3.0.6 on 2021-01-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0031_auto_20210110_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cidade_nasc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidade_nasc', to='coletas.Cidade', verbose_name='Cidade de Nascimento'),
        ),
    ]
