# Generated by Django 3.0.6 on 2021-01-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0032_paciente_cidade_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(default=0, max_length=200, verbose_name='Nome da Mãe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='jah_doencas',
            field=models.ManyToManyField(null=True, to='coletas.Doencas', verbose_name='Já teve alguma dessas doenças'),
        ),
    ]
