# Generated by Django 3.0.6 on 2021-01-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0033_auto_20210110_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(max_length=200, verbose_name='Nome da Mãe'),
        ),
    ]
