# Generated by Django 3.0.6 on 2021-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0036_auto_20210125_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dt_ini_trat',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início do Tratamento com o Grupo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sang',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('não sabe', 'não sabe')], max_length=16, null=True, verbose_name='Tipo Sanguíneo'),
        ),
    ]
