# Generated by Django 3.0.6 on 2021-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0037_auto_20210318_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tempo_rec',
            field=models.IntegerField(blank=True, verbose_name='Tempo de Recuperação (dias)'),
        ),
    ]
