# Generated by Django 3.0.6 on 2021-03-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0040_auto_20210324_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='outros_tratamentos',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Outros Tratamentos'),
        ),
    ]
