# Generated by Django 3.0.6 on 2021-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0041_auto_20210324_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='agravantes',
        ),
        migrations.AddField(
            model_name='paciente',
            name='agravantes',
            field=models.ManyToManyField(blank=True, null=True, to='coletas.Agravantes'),
        ),
    ]
