# Generated by Django 3.0.6 on 2021-03-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0042_auto_20210324_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='outros_tratamentos',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Outros Tratamentos'),
        ),
    ]
