# Generated by Django 3.0.6 on 2021-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0043_auto_20210324_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia10',
            field=models.BooleanField(blank=True, default=False, verbose_name='D10'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia11',
            field=models.BooleanField(blank=True, default=False, verbose_name='D11'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia12',
            field=models.BooleanField(blank=True, default=False, verbose_name='D12'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia13',
            field=models.BooleanField(blank=True, default=False, verbose_name='D13'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia14',
            field=models.BooleanField(blank=True, default=False, verbose_name='D14'),
        ),
        migrations.AddField(
            model_name='dias_sintoma',
            name='dia15',
            field=models.BooleanField(blank=True, default=False, verbose_name='D15'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia10',
            field=models.FloatField(blank=True, null=True, verbose_name='D10'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia11',
            field=models.FloatField(blank=True, null=True, verbose_name='D11'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia12',
            field=models.FloatField(blank=True, null=True, verbose_name='D12'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia13',
            field=models.FloatField(blank=True, null=True, verbose_name='D13'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia14',
            field=models.FloatField(blank=True, null=True, verbose_name='D14'),
        ),
        migrations.AddField(
            model_name='medicoes_dia',
            name='dia15',
            field=models.FloatField(blank=True, null=True, verbose_name='D15'),
        ),
    ]
