# Generated by Django 3.0.6 on 2021-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0044_auto_20210324_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='outros_tratamentos',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tempo_rec',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de uso da Invermectina'),
        ),
    ]
